config/routes.rb
Rails.application.routes.draw do

  resources :businesses do
  resources :reviews, except: [:show, :index]
  end


  devise_for :users, path_names: {sign_in: "signin", sign_out: "signout"}

  get 'welcome/index'

  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  root 'welcome#index'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]


  def index
    @businesses = Business.search(params[:category_id],params[:search])

  end

  def new
    @business = Business.new
  end

  def show
    @reviews = Review.where(business_id: @business.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  def edit
  end

  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to business_url, notice: 'Business has been successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_business
    @business = Business.find(params[:id])
  end

  def business_params
    params.require(:business).permit(:name, :address, :phone, :website, :image, :category_id, :image)
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for @business, :html => { :multipart => true } do |f| %>
    <% if @business.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><%= pluralize(@business.errors.count, "error") %> prohibited this listing from being saved:</h4>

          <ul>
            <% @business.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :category_id %><br />
      <%= f.collection_select :category_id, Category.order(:name), :id, :name, include_blank: true %>
    </div>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_area :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :phone %><br>
      <%= f.text_field :phone, class: "form-control" %>
    </div>

    </div>
    <div class="form-group">
      <%= f.label :website %><br>
      <%= f.text_field :website, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.file_field :image, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/businesses/edit.html.erb
<%= render 'form' %>

app/views/businesses/index.html.erb
<div class="jumbotron">
  <h1>Locate A business in Your Area!</h1>
  <%= form_tag businesses_path, :method => 'get', :id => "businesses_search" do %>

      <p class="styled-select slate">
        <%= select_tag :category_id, options_for_select([["Category", nil]] + Category.all.collect {|x| [x.name, x.id]}),{} %>
        <%= text_field_tag :search, params[:search], placeholder: 'eg city' %>
        <%= submit_tag "Search", :address => nil %>
      </p>
  <% end %>

</div>

  <table class="table table-hover table-condensed">
    <tr>
      <th class="center"></th>
      <th class="center">Name</th>
      <th class="center">Address</th>
      <th class="center">Phone</th>
      <th class="center">Website</th>
    </tr>
   <tbody>
  <% @businesses.each do |business| %>
      <tr>
        <td><%= image_tag business.image.url(:thumb) %></td>
        <td><%= business.name %></td>
         <td><%= business.address %></td>
         <td><%= business.phone %></td>
         <td><%= link_to business.website, business.website %></td>
        <td><%= link_to 'Show', business, class: "btn btn-link" %></td>

      </tr>
  <% end %>
   </tbody>
  </table>

app/views/businesses/new.html.erb
<%= render 'form' %>

app/views/businesses/show.html.erb
<div class="row">
  <div class="col-md-3">

<%= image_tag @business.image.url(:medium) %>

<h2>
  <%= @business.name %>
</h2>

 <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews" %></p>


    <strong>Address</strong>
<p>
<%= @business.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @business.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= link_to @business.website, @business.website %>

</p>

<%= link_to "Write Review", new_business_review_path(@business), class: "btn btn-primary" %>

    <iframe
    width="230"
    height="230"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBJg0HiO2KtvExTuiWB6rKhmUUsHXFk6dY
        &q=<%= @business.address.parameterize %>&zoom=14">    </iframe>

  </div>

  <div class="col-md-9">
    <% if @reviews.blank? %>
        <h3>No reviews yet. Be the first to write one!</h3>
    <% else %>

    <table class="table">
     <tbody>
     <% @reviews.each do |review| %>
	  <tr>
	    <td>
	      <div class="star-rating" data-score= <%= review.rating %>></div>
	      <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>
	    </td>
	  </tr>
      <% end %>
     </tbody>
    </table>
    <% end %>

  </div>
</div>

<%= link_to 'Edit', edit_business_path(@business), class: "btn btn-link" %> |

<%= link_to 'Back', businesses_path, class: "btn btn-link" %>

<script>
	$('.star-rating').raty({
		path: 'https://s3.amazonaws.com/global-market/stars',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>