config/routes.rb
Rails.application.routes.draw do

  resources :businesses do
  resources :reviews, except: [:show, :index]
  end


  devise_for :users, path_names: {sign_in: "signin", sign_out: "signout"}

  get 'welcome/index'

  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  root 'welcome#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_business



  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.business_id = @business.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to @business, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
        end
        end
    end


  def update
    @review.update(review_params)
  end

  def destroy
    @review.destroy
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

  def set_business
    @business = Business.find(params[:business_id])
  end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@business, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div id="star-rating"></div>

    <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>


<script>
	$('#star-rating').raty({
		path: 'https://s3.amazonaws.com/yelpdemo77/Stars',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', '#'%> |
<%= link_to 'Back', business_path(@business) %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', business_path(@business) %>